### ISSUE TITLE
After renaming submodules fails with

### ISSUE THREAD

**Issue by Ntemis** [FluBBaOfWard/JailBreakDS#1]
linking JailBreakDS.elf
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: FileHandling.o: in function `loadRoms':
/home/demetris/Desktop/Development/JailBreakDS/arm9/source/FileHandling.c:216: undefined reference to `findFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/JailBreakDS/arm9/source/FileHandling.c:218: undefined reference to `loadFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/JailBreakDS/arm9/source/FileHandling.c:226: undefined reference to `findFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/JailBreakDS/arm9/source/FileHandling.c:228: undefined reference to `loadFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: FileHelper.o: in function `loadROM':
/home/demetris/Desktop/Development/JailBreakDS/arm9/source/Shared/FileHelper.c:69: undefined reference to `loadFileTypeInZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/JailBreakDS/arm9/source/Shared/FileHelper.c:89: undefined reference to `cenHead'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/JailBreakDS/arm9/source/Shared/FileHelper.c:89: undefined reference to `zipFilename'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/JailBreakDS/arm9/source/Shared/FileHelper.c:89: undefined reference to `zipError'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/demetris/Desktop/Development/JailBreakDS/arm9/Makefile:129: /home/demetris/Desktop/Development/JailBreakDS/arm9/JailBreakDS.elf] Error 1
make[1]: *** [Makefile:113: build] Error 2
make[1]: Leaving directory '/home/demetris/Desktop/Development/JailBreakDS/arm9'
make: *** [Makefile:39: arm9/JailBreakDS.elf] Error 2

**Comment by FluBBaOfWard** [comment]
Pushed source.

**Comment by Ntemis** [comment]
gtg
